"""initial sovereign core schema (aligned with v1.7 ORM)"""
from alembic import op
import sqlalchemy as sa
revision = '0001_initial_core'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    op.create_table('tenants', sa.Column('id',sa.Integer(),primary_key=True), sa.Column('name',sa.String(200),nullable=False), sa.Column('status',sa.String(20),nullable=False))
    op.create_table('users', sa.Column('id',sa.String(255),primary_key=True), sa.Column('email',sa.String(320),nullable=False,unique=True), sa.Column('active',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('tenant_memberships', sa.Column('id',sa.Integer(),primary_key=True), sa.Column('user_id',sa.String(255),sa.ForeignKey('users.id',ondelete='CASCADE'),nullable=False), sa.Column('tenant_id',sa.Integer(),sa.ForeignKey('tenants.id',ondelete='CASCADE'),nullable=False), sa.Column('role',sa.String(50),nullable=False), sa.Column('active',sa.Boolean(),nullable=False,server_default=sa.true()), sa.UniqueConstraint('user_id','tenant_id',name='uq_membership_user_tenant'))
    op.create_table('roles', sa.Column('id',sa.Integer(),primary_key=True), sa.Column('code',sa.String(100),nullable=False,unique=True), sa.Column('name',sa.String(200),nullable=False))
    op.create_table('permissions', sa.Column('id',sa.Integer(),primary_key=True), sa.Column('code',sa.String(150),nullable=False,unique=True), sa.Column('name',sa.String(200),nullable=False))
    op.create_table('role_permissions', sa.Column('id',sa.Integer(),primary_key=True), sa.Column('role_id',sa.Integer(),sa.ForeignKey('roles.id'),nullable=False), sa.Column('permission_id',sa.Integer(),sa.ForeignKey('permissions.id'),nullable=False), sa.UniqueConstraint('role_id','permission_id'))
    op.create_table('membership_roles', sa.Column('id',sa.Integer(),primary_key=True), sa.Column('membership_id',sa.Integer(),sa.ForeignKey('tenant_memberships.id'),nullable=False), sa.Column('role_id',sa.Integer(),sa.ForeignKey('roles.id'),nullable=False), sa.UniqueConstraint('membership_id','role_id'))
    op.create_table('audit_records', sa.Column('id',sa.Integer(),primary_key=True), sa.Column('tenant_id',sa.Integer(),sa.ForeignKey('tenants.id'),nullable=False), sa.Column('actor_id',sa.String(255),nullable=False), sa.Column('action',sa.String(120),nullable=False), sa.Column('subject',sa.String(120),nullable=False), sa.Column('subject_id',sa.String(255),nullable=False), sa.Column('metadata_json',sa.Text(),nullable=False), sa.Column('occurred_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('idempotency_records', sa.Column('id',sa.Integer(),primary_key=True), sa.Column('tenant_id',sa.Integer(),sa.ForeignKey('tenants.id'),nullable=False), sa.Column('key',sa.String(255),nullable=False), sa.Column('request_hash',sa.String(128),nullable=False), sa.Column('response_json',sa.Text(),nullable=False), sa.UniqueConstraint('tenant_id','key',name='uq_idempotency_tenant_key'))
    op.create_table('outbox_events', sa.Column('id',sa.Integer(),primary_key=True), sa.Column('event_id',sa.String(64),nullable=False,unique=True), sa.Column('tenant_id',sa.Integer(),sa.ForeignKey('tenants.id'),nullable=False), sa.Column('event_type',sa.String(200),nullable=False), sa.Column('aggregate_type',sa.String(100),nullable=False), sa.Column('aggregate_id',sa.String(100),nullable=False), sa.Column('payload',sa.JSON(),nullable=False), sa.Column('published',sa.Boolean(),nullable=False,server_default=sa.false()))
    op.create_table('journals', sa.Column('id',sa.Integer(),primary_key=True), sa.Column('tenant_id',sa.Integer(),sa.ForeignKey('tenants.id'),nullable=False), sa.Column('reference',sa.String(255),nullable=False), sa.Column('currency',sa.String(10),nullable=False), sa.Column('status',sa.String(20),nullable=False), sa.Column('created_at',sa.DateTime(timezone=True),nullable=False), sa.UniqueConstraint('tenant_id','reference',name='uq_journal_tenant_reference'))
    op.create_table('journal_lines', sa.Column('id',sa.Integer(),primary_key=True), sa.Column('journal_id',sa.Integer(),sa.ForeignKey('journals.id',ondelete='CASCADE'),nullable=False), sa.Column('account',sa.String(120),nullable=False), sa.Column('debit',sa.Numeric(20,4),nullable=False), sa.Column('credit',sa.Numeric(20,4),nullable=False))
    op.create_table('fiscal_periods', sa.Column('id',sa.Integer(),primary_key=True), sa.Column('tenant_id',sa.Integer(),sa.ForeignKey('tenants.id',ondelete='CASCADE'),nullable=False), sa.Column('name',sa.String(100),nullable=False), sa.Column('starts_on',sa.Date(),nullable=False), sa.Column('ends_on',sa.Date(),nullable=False), sa.Column('closed',sa.Boolean(),nullable=False,server_default=sa.false()), sa.UniqueConstraint('tenant_id','name',name='uq_period_tenant_name'))
    op.create_table('exchange_rates', sa.Column('id',sa.Integer(),primary_key=True), sa.Column('tenant_id',sa.Integer(),sa.ForeignKey('tenants.id',ondelete='CASCADE'),nullable=False), sa.Column('base_currency',sa.String(10),nullable=False), sa.Column('quote_currency',sa.String(10),nullable=False), sa.Column('rate',sa.Numeric(20,8),nullable=False), sa.Column('effective_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('journal_links', sa.Column('id',sa.Integer(),primary_key=True), sa.Column('tenant_id',sa.Integer(),sa.ForeignKey('tenants.id',ondelete='CASCADE'),nullable=False), sa.Column('journal_id',sa.Integer(),sa.ForeignKey('journals.id',ondelete='CASCADE'),nullable=False), sa.Column('reversal_of_journal_id',sa.Integer(),sa.ForeignKey('journals.id'),nullable=False), sa.UniqueConstraint('tenant_id','reversal_of_journal_id',name='uq_one_reversal_per_journal'))
    op.create_table('inventory_items', sa.Column('id',sa.String(255),primary_key=True), sa.Column('tenant_id',sa.Integer(),sa.ForeignKey('tenants.id',ondelete='CASCADE'),primary_key=True,nullable=False), sa.Column('name',sa.String(255),nullable=False), sa.Column('unit_code',sa.String(30),nullable=False), sa.Column('active',sa.Boolean(),nullable=False,server_default=sa.true()), sa.UniqueConstraint('tenant_id','id',name='uq_inventory_item_tenant_id'))
    op.create_table('warehouses', sa.Column('id',sa.String(255),primary_key=True), sa.Column('tenant_id',sa.Integer(),sa.ForeignKey('tenants.id',ondelete='CASCADE'),primary_key=True,nullable=False), sa.Column('name',sa.String(255),nullable=False), sa.Column('allow_negative_stock',sa.Boolean(),nullable=False,server_default=sa.false()), sa.Column('active',sa.Boolean(),nullable=False,server_default=sa.true()), sa.UniqueConstraint('tenant_id','id',name='uq_warehouse_tenant_id'))
    op.create_table('inventory_movements', sa.Column('id',sa.Integer(),primary_key=True), sa.Column('tenant_id',sa.Integer(),sa.ForeignKey('tenants.id',ondelete='CASCADE'),nullable=False), sa.Column('item_id',sa.String(255),nullable=False), sa.Column('warehouse_id',sa.String(255),nullable=False), sa.Column('destination_warehouse_id',sa.String(255),nullable=True), sa.Column('quantity',sa.Numeric(20,4),nullable=False), sa.Column('direction',sa.String(20),nullable=False), sa.Column('reference',sa.String(255),nullable=False), sa.Column('created_at',sa.DateTime(timezone=True),nullable=False), sa.UniqueConstraint('tenant_id','reference',name='uq_inventory_movement_tenant_reference'), sa.CheckConstraint('quantity > 0',name='ck_inventory_movement_positive_quantity'), sa.CheckConstraint("direction IN ('in','out','transfer')",name='ck_inventory_movement_direction'))
    op.create_table('inventory_reservations', sa.Column('id',sa.Integer(),primary_key=True), sa.Column('tenant_id',sa.Integer(),sa.ForeignKey('tenants.id',ondelete='CASCADE'),nullable=False), sa.Column('item_id',sa.String(255),nullable=False), sa.Column('warehouse_id',sa.String(255),nullable=False), sa.Column('quantity',sa.Numeric(20,4),nullable=False), sa.Column('reference',sa.String(255),nullable=False), sa.Column('status',sa.String(20),nullable=False), sa.Column('created_at',sa.DateTime(timezone=True),nullable=False), sa.UniqueConstraint('tenant_id','reference',name='uq_reservation_tenant_reference'), sa.CheckConstraint('quantity > 0',name='ck_reservation_positive_quantity'), sa.CheckConstraint("status IN ('active','released','fulfilled')",name='ck_reservation_status'))

def downgrade():
    for name in ['inventory_reservations','inventory_movements','warehouses','inventory_items','journal_links','exchange_rates','fiscal_periods','journal_lines','journals','outbox_events','idempotency_records','audit_records','membership_roles','role_permissions','permissions','roles','tenant_memberships','users','tenants']:
        op.drop_table(name)
