from alembic import op
import sqlalchemy as sa
revision='0007_workflows'; down_revision='0006_logistics'; branch_labels=None; depends_on=None

def upgrade():
    op.create_table('workflow_definitions',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('tenant_id',sa.Integer(),sa.ForeignKey('tenants.id',ondelete='CASCADE'),nullable=False),sa.Column('code',sa.String(120),nullable=False),sa.Column('version',sa.Integer(),nullable=False),sa.Column('name',sa.String(255),nullable=False),sa.Column('definition_json',sa.JSON(),nullable=False),sa.Column('active',sa.Boolean(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('tenant_id','code','version',name='uq_workflow_definition_tenant_code_version'),sa.CheckConstraint('version > 0',name='ck_workflow_definition_positive_version'))
    op.create_index('ix_workflow_definitions_tenant_id','workflow_definitions',['tenant_id'])
    op.create_table('workflow_instances',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('tenant_id',sa.Integer(),sa.ForeignKey('tenants.id',ondelete='CASCADE'),nullable=False),sa.Column('definition_id',sa.Integer(),sa.ForeignKey('workflow_definitions.id',ondelete='RESTRICT'),nullable=False),sa.Column('reference',sa.String(255),nullable=False),sa.Column('aggregate_type',sa.String(100),nullable=False),sa.Column('aggregate_id',sa.String(255),nullable=False),sa.Column('current_step',sa.String(120),nullable=False),sa.Column('status',sa.String(30),nullable=False),sa.Column('context_json',sa.JSON(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('tenant_id','reference',name='uq_workflow_instance_tenant_reference'),sa.CheckConstraint("status IN ('running','waiting','completed','failed','cancelled')",name='ck_workflow_instance_status'))
    op.create_index('ix_workflow_instances_tenant_id','workflow_instances',['tenant_id']); op.create_index('ix_workflow_instances_definition_id','workflow_instances',['definition_id'])
    op.create_table('workflow_transitions',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('tenant_id',sa.Integer(),sa.ForeignKey('tenants.id',ondelete='CASCADE'),nullable=False),sa.Column('instance_id',sa.Integer(),sa.ForeignKey('workflow_instances.id',ondelete='CASCADE'),nullable=False),sa.Column('event_id',sa.String(255),nullable=False),sa.Column('from_step',sa.String(120),nullable=False),sa.Column('to_step',sa.String(120),nullable=False),sa.Column('event_type',sa.String(200),nullable=False),sa.Column('payload_json',sa.JSON(),nullable=False),sa.Column('occurred_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('tenant_id','event_id',name='uq_workflow_transition_tenant_event'))
    op.create_index('ix_workflow_transitions_tenant_id','workflow_transitions',['tenant_id']); op.create_index('ix_workflow_transitions_instance_id','workflow_transitions',['instance_id'])
    op.create_table('workflow_tasks',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('tenant_id',sa.Integer(),sa.ForeignKey('tenants.id',ondelete='CASCADE'),nullable=False),sa.Column('instance_id',sa.Integer(),sa.ForeignKey('workflow_instances.id',ondelete='CASCADE'),nullable=False),sa.Column('step',sa.String(120),nullable=False),sa.Column('task_key',sa.String(255),nullable=False),sa.Column('status',sa.String(30),nullable=False),sa.Column('attempts',sa.Integer(),nullable=False),sa.Column('last_error',sa.Text()),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('tenant_id','instance_id','task_key',name='uq_workflow_task_tenant_instance_key'),sa.CheckConstraint("status IN ('pending','running','succeeded','failed','cancelled')",name='ck_workflow_task_status'),sa.CheckConstraint('attempts >= 0',name='ck_workflow_task_attempts_nonnegative'))
    op.create_index('ix_workflow_tasks_tenant_id','workflow_tasks',['tenant_id']); op.create_index('ix_workflow_tasks_instance_id','workflow_tasks',['instance_id'])

def downgrade():
    for idx, table in [('ix_workflow_tasks_instance_id','workflow_tasks'),('ix_workflow_tasks_tenant_id','workflow_tasks'),('ix_workflow_transitions_instance_id','workflow_transitions'),('ix_workflow_transitions_tenant_id','workflow_transitions'),('ix_workflow_instances_definition_id','workflow_instances'),('ix_workflow_instances_tenant_id','workflow_instances'),('ix_workflow_definitions_tenant_id','workflow_definitions')]: op.drop_index(idx,table_name=table)
    op.drop_table('workflow_tasks'); op.drop_table('workflow_transitions'); op.drop_table('workflow_instances'); op.drop_table('workflow_definitions')
