from alembic import op
import sqlalchemy as sa
revision='0013_marketplace'; down_revision='0012_ai_intelligence'; branch_labels=None; depends_on=None

def upgrade():
    op.create_table('marketplace_seller_profiles',
        sa.Column('tenant_id',sa.Integer(),sa.ForeignKey('tenants.id',ondelete='CASCADE'),primary_key=True), sa.Column('slug',sa.String(120),nullable=False,unique=True), sa.Column('display_name',sa.String(200),nullable=False), sa.Column('description',sa.Text(),nullable=False,server_default=''), sa.Column('seller_type',sa.String(30),nullable=False,server_default='business'), sa.Column('status',sa.String(20),nullable=False,server_default='pending'), sa.Column('created_at',sa.DateTime(timezone=True),nullable=False), sa.CheckConstraint("seller_type IN ('business','individual','institution')",name='ck_market_seller_type'), sa.CheckConstraint("status IN ('pending','active','suspended','closed')",name='ck_market_seller_status'))
    op.create_table('marketplace_categories', sa.Column('id',sa.Integer(),primary_key=True), sa.Column('parent_id',sa.Integer(),sa.ForeignKey('marketplace_categories.id',ondelete='SET NULL')), sa.Column('slug',sa.String(120),nullable=False,unique=True), sa.Column('name',sa.String(200),nullable=False), sa.Column('active',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('marketplace_listings',
        sa.Column('id',sa.Integer(),primary_key=True), sa.Column('seller_tenant_id',sa.Integer(),sa.ForeignKey('tenants.id',ondelete='CASCADE'),nullable=False), sa.Column('item_id',sa.String(255)), sa.Column('warehouse_id',sa.String(255)), sa.Column('category_id',sa.Integer(),sa.ForeignKey('marketplace_categories.id',ondelete='SET NULL')), sa.Column('slug',sa.String(180),nullable=False), sa.Column('title',sa.String(300),nullable=False), sa.Column('description',sa.Text(),nullable=False,server_default=''), sa.Column('listing_type',sa.String(20),nullable=False,server_default='product'), sa.Column('currency',sa.String(10),nullable=False), sa.Column('unit_price',sa.Numeric(20,4),nullable=False), sa.Column('status',sa.String(20),nullable=False,server_default='draft'), sa.Column('stock_policy',sa.String(20),nullable=False,server_default='managed'), sa.Column('created_at',sa.DateTime(timezone=True),nullable=False), sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False), sa.UniqueConstraint('seller_tenant_id','slug',name='uq_market_listing_seller_slug'), sa.CheckConstraint("listing_type IN ('product','service')",name='ck_market_listing_type'), sa.CheckConstraint("status IN ('draft','published','paused','archived')",name='ck_market_listing_status'), sa.CheckConstraint("stock_policy IN ('managed','unmanaged')",name='ck_market_listing_stock_policy'), sa.CheckConstraint('unit_price >= 0',name='ck_market_listing_price_nonnegative'), sa.CheckConstraint("(listing_type = 'product' AND item_id IS NOT NULL AND warehouse_id IS NOT NULL) OR listing_type = 'service'",name='ck_market_listing_product_refs'))
    op.create_index('ix_market_listing_public','marketplace_listings',['status','category_id','seller_tenant_id'])
    op.create_table('marketplace_buyer_profiles',sa.Column('user_id',sa.String(255),sa.ForeignKey('users.id',ondelete='CASCADE'),primary_key=True),sa.Column('display_name',sa.String(200),nullable=False),sa.Column('phone',sa.String(50)),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('marketplace_addresses',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('user_id',sa.String(255),sa.ForeignKey('users.id',ondelete='CASCADE'),nullable=False),sa.Column('label',sa.String(80),nullable=False),sa.Column('recipient_name',sa.String(200),nullable=False),sa.Column('phone',sa.String(50),nullable=False),sa.Column('governorate',sa.String(120),nullable=False),sa.Column('city',sa.String(120),nullable=False),sa.Column('address_line',sa.String(500),nullable=False),sa.Column('landmark',sa.String(300)),sa.Column('active',sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False)); op.create_index('ix_marketplace_addresses_user_id','marketplace_addresses',['user_id'])
    op.create_table('marketplace_carts',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('buyer_user_id',sa.String(255),sa.ForeignKey('users.id',ondelete='CASCADE'),nullable=False,unique=True),sa.Column('status',sa.String(20),nullable=False,server_default='active'),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.CheckConstraint("status IN ('active','checked_out','abandoned')",name='ck_market_cart_status'))
    op.create_table('marketplace_cart_items',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('cart_id',sa.Integer(),sa.ForeignKey('marketplace_carts.id',ondelete='CASCADE'),nullable=False),sa.Column('listing_id',sa.Integer(),sa.ForeignKey('marketplace_listings.id',ondelete='RESTRICT'),nullable=False),sa.Column('quantity',sa.Numeric(20,4),nullable=False),sa.Column('added_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('cart_id','listing_id',name='uq_market_cart_listing'),sa.CheckConstraint('quantity > 0',name='ck_market_cart_quantity_positive'))
    op.create_index('ix_marketplace_cart_items_cart_id','marketplace_cart_items',['cart_id'])
    op.create_table('marketplace_orders',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('reference',sa.String(255),nullable=False,unique=True),sa.Column('buyer_user_id',sa.String(255),sa.ForeignKey('users.id',ondelete='RESTRICT'),nullable=False),sa.Column('seller_tenant_id',sa.Integer(),sa.ForeignKey('tenants.id',ondelete='RESTRICT'),nullable=False),sa.Column('sales_order_id',sa.Integer(),sa.ForeignKey('sales_orders.id',ondelete='SET NULL'),unique=True),sa.Column('shipping_address_id',sa.Integer(),sa.ForeignKey('marketplace_addresses.id',ondelete='SET NULL')),sa.Column('currency',sa.String(10),nullable=False),sa.Column('subtotal',sa.Numeric(20,4),nullable=False),sa.Column('shipping_fee',sa.Numeric(20,4),nullable=False,server_default='0'),sa.Column('platform_fee',sa.Numeric(20,4),nullable=False,server_default='0'),sa.Column('total',sa.Numeric(20,4),nullable=False),sa.Column('status',sa.String(30),nullable=False,server_default='pending_payment'),sa.Column('payment_reference',sa.String(255)),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.CheckConstraint("status IN ('pending_payment','paid','processing','shipped','delivered','completed','cancelled','refunded','disputed')",name='ck_market_order_status'),sa.CheckConstraint('subtotal >= 0 AND shipping_fee >= 0 AND platform_fee >= 0 AND total >= 0',name='ck_market_order_amounts_nonnegative'))
    op.create_index('ix_marketplace_orders_buyer_user_id','marketplace_orders',['buyer_user_id']); op.create_index('ix_marketplace_orders_seller_tenant_id','marketplace_orders',['seller_tenant_id']); op.create_index('ix_marketplace_listings_item_id','marketplace_listings',['item_id']); op.create_index('ix_marketplace_listings_seller_tenant_id','marketplace_listings',['seller_tenant_id'])
    op.create_table('marketplace_order_lines',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('marketplace_order_id',sa.Integer(),sa.ForeignKey('marketplace_orders.id',ondelete='CASCADE'),nullable=False),sa.Column('listing_id',sa.Integer(),sa.ForeignKey('marketplace_listings.id',ondelete='RESTRICT'),nullable=False),sa.Column('sales_order_line_id',sa.Integer(),sa.ForeignKey('sales_order_lines.id',ondelete='SET NULL')),sa.Column('title_snapshot',sa.String(300),nullable=False),sa.Column('quantity',sa.Numeric(20,4),nullable=False),sa.Column('unit_price',sa.Numeric(20,4),nullable=False),sa.Column('line_total',sa.Numeric(20,4),nullable=False),sa.CheckConstraint('quantity > 0 AND unit_price >= 0 AND line_total >= 0',name='ck_market_order_line_amounts')); op.create_index('ix_marketplace_order_lines_marketplace_order_id','marketplace_order_lines',['marketplace_order_id'])
    op.create_table('marketplace_payouts',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('seller_tenant_id',sa.Integer(),sa.ForeignKey('tenants.id',ondelete='RESTRICT'),nullable=False),sa.Column('marketplace_order_id',sa.Integer(),sa.ForeignKey('marketplace_orders.id',ondelete='RESTRICT'),nullable=False,unique=True),sa.Column('reference',sa.String(255),nullable=False,unique=True),sa.Column('gross_amount',sa.Numeric(20,4),nullable=False),sa.Column('platform_fee',sa.Numeric(20,4),nullable=False),sa.Column('net_amount',sa.Numeric(20,4),nullable=False),sa.Column('currency',sa.String(10),nullable=False),sa.Column('status',sa.String(20),nullable=False,server_default='held'),sa.Column('eligible_at',sa.DateTime(timezone=True)),sa.Column('paid_at',sa.DateTime(timezone=True)),sa.CheckConstraint("status IN ('held','eligible','paid','reversed')",name='ck_market_payout_status'),sa.CheckConstraint('gross_amount >= platform_fee AND net_amount = gross_amount - platform_fee',name='ck_market_payout_math'))
    op.create_index('ix_marketplace_payouts_seller_tenant_id','marketplace_payouts',['seller_tenant_id'])
    op.create_table('marketplace_reviews',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('marketplace_order_id',sa.Integer(),sa.ForeignKey('marketplace_orders.id',ondelete='CASCADE'),nullable=False),sa.Column('listing_id',sa.Integer(),sa.ForeignKey('marketplace_listings.id',ondelete='RESTRICT'),nullable=False),sa.Column('buyer_user_id',sa.String(255),sa.ForeignKey('users.id',ondelete='RESTRICT'),nullable=False),sa.Column('rating',sa.Integer(),nullable=False),sa.Column('title',sa.String(200),nullable=False,server_default=''),sa.Column('body',sa.Text(),nullable=False,server_default=''),sa.Column('status',sa.String(20),nullable=False,server_default='published'),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('marketplace_order_id','listing_id','buyer_user_id',name='uq_market_review_once'),sa.CheckConstraint('rating BETWEEN 1 AND 5',name='ck_market_review_rating'),sa.CheckConstraint("status IN ('published','hidden','removed')",name='ck_market_review_status'))
    op.create_table('marketplace_disputes',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('marketplace_order_id',sa.Integer(),sa.ForeignKey('marketplace_orders.id',ondelete='RESTRICT'),nullable=False,unique=True),sa.Column('opened_by_user_id',sa.String(255),sa.ForeignKey('users.id',ondelete='RESTRICT'),nullable=False),sa.Column('reason',sa.String(120),nullable=False),sa.Column('description',sa.Text(),nullable=False),sa.Column('status',sa.String(20),nullable=False,server_default='open'),sa.Column('resolution',sa.Text()),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('resolved_at',sa.DateTime(timezone=True)),sa.CheckConstraint("status IN ('open','investigating','resolved','rejected','cancelled')",name='ck_market_dispute_status'))

def downgrade():
    op.drop_table('marketplace_disputes'); op.drop_table('marketplace_reviews'); op.drop_index('ix_marketplace_payouts_seller_tenant_id',table_name='marketplace_payouts'); op.drop_table('marketplace_payouts'); op.drop_index('ix_marketplace_order_lines_marketplace_order_id',table_name='marketplace_order_lines'); op.drop_table('marketplace_order_lines'); op.drop_index('ix_marketplace_orders_seller_tenant_id',table_name='marketplace_orders'); op.drop_index('ix_marketplace_orders_buyer_user_id',table_name='marketplace_orders'); op.drop_table('marketplace_orders'); op.drop_index('ix_market_cart_items_cart_id',table_name='marketplace_cart_items'); op.drop_table('marketplace_cart_items'); op.drop_table('marketplace_carts'); op.drop_index('ix_marketplace_addresses_user_id',table_name='marketplace_addresses'); op.drop_table('marketplace_addresses'); op.drop_table('marketplace_buyer_profiles'); op.drop_index('ix_market_listing_public',table_name='marketplace_listings'); op.drop_table('marketplace_listings'); op.drop_table('marketplace_categories'); op.drop_table('marketplace_seller_profiles')
